### ISSUE TITLE
Publish non-minified JS files on npm

### ISSUE THREAD

**Issue by mvorisek** [fiduswriter/diffDOM#121]
Non-minified/beatified JS are defacto standard and are very handy for debugging.

I know there are `.map` files present, but they cannot be used all the time, not mentioning the JS files are sometimes needed to be edited for the actual debugging which is not possible now without fully rebuilding from TS.

This is a feature request to publish both non-minified JS files (`.js`) and minified (`.min.js`) on npm.

**Comment by johanneswilm** [comment]
Hey @mvorisek,
do you have a link describing this standard? I am interested how the non-minified versions are referenced in the package.json file according to this standard.

**Comment by mvorisek** [comment]
It is a convention, we use for ex. `@highlightjs/cdn-assets`, `flatpickr`, `jquery`, ... and all bundle both versions (minified/non-minified).

**Comment by AlexErrant** [comment]
FWIW non-minified files also make it possible to use [PNPM patch](https://pnpm.io/cli/patch)/[Yarn patch](https://yarnpkg.com/cli/patch), should one need to tweak deeply intrinsic behavior. Devs can't feasibly patch minified files.

**Comment by mvorisek** [comment]
@johanneswilm we use `browser/diffDOM.js` file which is still minimized. The fix in https://github.com/fiduswriter/diffDOM/commit/4f7443a5454d0b60582553449919edef6d0e4ec6 needs to be done for this file too.

**Comment by johanneswilm** [comment]
That is supposed to be an end-user file so I'm thinking it probably should
be minifiee. Do you not have any minification set up yourself?

**Comment by mvorisek** [comment]
We use this end user file. Please distribute both versions, one minified, one not minified. There are many usecases why it is needed, for debugging, patching like mentioned above...

**Comment by johanneswilm** [comment]
Can you explain what you need to patch it for? Note that there is an LGPL
license, so it might make more sense to add specific hooks/configuration
options.
If this was the main usecase, then I wonder if it would make more sense for
you to adapt a build chain including minification/transpilation instead.

**Comment by mvorisek** [comment]
We download dist/browser files using npm and distribute them with our app. When debug is enabled, we offer non-minified files. We do not have any intermediate transpilation in between. For this usecase, we need minified and non-minified builds as other JS libs have.

**Comment by johanneswilm** [comment]
OK, I think you should need to transpile it then. How else will you control
what browser versions, etc. you want to make it available for? Transpiling
JS has been fairly standard since ES2015, hasn't it?

And what do you need to patch it for? Is there a hook or configuration
option that you need to use?

**Comment by mvorisek** [comment]
I know, but this is our workflow and it enables the end developer of out app to enable/disable libraries. We version them using VCS. Would you please accept a patch like https://github.com/fiduswriter/diffDOM/commit/4f7443a5454d0b60582553449919edef6d0e4ec6 for the browser JS as well?

**Comment by johanneswilm** [comment]
@mvorisek I think I'll revert https://github.com/fiduswriter/diffDOM/commit/4f7443a5454d0b60582553449919edef6d0e4ec6 as I don't really see a point with it other than to make it possible to circumvent the LGPL by patching the library without making the patch public (questionable whether that would hold up in court, but some may try). 

After reading on this topic, I saw some people recommended not minifying the base version (after transpiling from TS) as that will in some instances make it easier for the final minifiers/transpilers to create the final output version. It would certainly not be a good idea to try to debug based on that non-minified version or to distribute it to end users.

I really want to support your case, but if it's just that you don't want to use a transpiler yet want to be able to debug, then I think you simply need to add a minifier/transpiler on your side. If you need me to add hooks or configuration options, I'm open to that as well. But I'll need to know where.

**Comment by johanneswilm** [comment]
@mvorisek There are several issues distributing like this, which means it's not a good idea:

* If you start sending out our files to your end users without a transpilation step, eventually there will be a case where your user requires support for say a specific version of Opera, or an old version of Safari that is particularly important in one country. And our latest version no longer transpile for that browser. So you'll file a ticket here, asking us to change the transpilation setting also to include that browser. Not good. Much better if you do the transpilation yourself and have full control over it.

* If you patch the library in some way, as suggested by @AlexErrant and yourself, then that means we are potentially locked into specific functions that have to be called in a particular way in order for your app not to break - and I won't even know which. If it's several groups doing it, it may be entirely impossible to release new versions without breaking it for some of them. And once it does break, you will be filing issues here. Much better to let us know where you need hooks or configuration options so that they can be respected from version to version - also to avoid potential license issues later on.

**Comment by mvorisek** [comment]
Please keep both minified/non-minified versions and for both files. We can discuss all the usecases, but in the end of the day, there are no negatives when providing both versions. This is also how major JS libs like jQuery etc. are distributed.

**Comment by johanneswilm** [comment]
jQuery is (mostly) pre-ES2015 legacy software.

And yes, I consider the above negatives. I don't think it is a good idea for others to ship a product that relies on a particular transpiler setting. And it's an even worse idea if others are patching the library in random ways instead of going through well-defined hooks and configuration options.

The only valid use for a non-minified version that I can see is that a minification/transpiling to earlier ES versions can make the packager of the end user be less efficient. It is not ever recommended to use those non-minified pieces of software in the browsers of end users.
