### ISSUE TITLE
Iframes

### ISSUE THREAD

**Issue by nexon33** [fiduswriter/diffDOM#126]
How do I dynamically update content inside iframes?

I am currently trying something like 

```
    var diff = dd.diff(document.getElementById('ifr').contentDocument.body.outerHTML , diffDOM.stringToObj('<body><p>test</p></body>'));
  console.log('diff', diff);
  
  var result = dd.apply(document.getElementById('ifr').contentDocument.body, diff);
  console.log('applied', result);
```

But I just get applied false.

edit: Here is a JS fiddle [https://jsfiddle.net/xazh91bk/3/](https://jsfiddle.net/xazh91bk/3/)

**Comment by mflorea** [comment]
I think this is a regression introduced in version 5.0 where checks like:

    aNode.nodeName === "#text"

have been replaced with:

    aNode instanceof Text

which is always false if ``diffDOM`` is loaded on the main window and the node is taken from an iframe, because the iframe has its own window with its own ``Text`` type, different from the one of the main window.

**Comment by johanneswilm** [comment]
I see. So adding something like `TextIframeElememt` as an alternative type should work? Does this only affect iframes or also other types?

**Comment by mflorea** [comment]
The suggestion on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms is to do something like:

    aNode instanceof aNode.ownerDocument.defaultView.Text

but this assumes ``aNode`` is a DOM node, so it needs some bulletproofing. Moreover, ``instanceof`` fails if the right side is undefined. Also, ``defaultView`` makes sense in the browser context (where there is a window) but not in the node context, where there is no window AFAIK. So overall I feel the usage of ``instanceof`` (in this context) creates more problems than it fixes. Was the previous check that bad? There is also the option to check for

    aNode.nodeType === Node.TEXT_NODE

see https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType , which works even if ``aNode`` and ``Node`` are from different realms / windows because the node type is a number and ``Node.TEXT_NODE`` has the same (primitive) value on all realms.

**Comment by johanneswilm** [comment]
Well, the typescript interpreter seems to prefer or require an instanceof check.  And Typescript is the new religion, so not sure what we can do about that.

**Comment by johanneswilm** [comment]
@mflorea Could you check whether this works for your usecase? If yes, we can make a release. If not, feel free to propose other improvements as long as they work for typescript.

**Comment by mflorea** [comment]
Hi @johanneswilm, thanks for the quick change. It's a step forward, meaning that now I can obtain the diff (patch) but I still cannot apply it because ``apply.ts`` is still using ``instanceof`` directly in a couple of places. My use case is this:

* I have a WYSIWYG editor that is using an iframe for the editing area
* I receive a content update (new HTML) and I want to apply the changes without disrupting too much the user currently editing
* For this I compute the diff between the new HTML and the HTML from the iframe <- this works fine now
* Then I apply the diff (patch) to the document from the iframe <- this still doesn't work (due to the usage of ``instanceof TypeFromMainWindow``)

Is it possible to apply the same fix to ``apply.ts``? Thanks again for providing and maintaining this great JavaScript library!

**Comment by johanneswilm** [comment]
@mflorea Could you take a look now? And make any adjustments you think are necessary? Then I can cut a release.

**Comment by mflorea** [comment]
@johanneswilm your latest changes work for me (my automated tests are passing). I only added a suggestion as a comment. From my point of view you can release (with or without my suggestion). Thanks again for the prompt response.

**Comment by johanneswilm** [comment]
Hey @mflorea in 5.2.0 I have now fixed this in another, simpler way that should work for your case as well.
