### ISSUE TITLE
nodeToObj, stringToObj uppercase mishaps

### ISSUE THREAD

**Issue by kapouer** [fiduswriter/diffDOM#128]
This
https://github.com/fiduswriter/diffDOM/commit/1b3cfe7737ea62c93050658dea2217cef16eabb0
makes this comparison fails
https://github.com/fiduswriter/diffDOM/blob/24a11daa2d77df5885e019c086bfae514e43540c/src/diffDOM/virtual/diff.ts#L180C20-L180C20
when comparing a dom node to an html string.

**Comment by johanneswilm** [comment]
@kapouer What is the issue for you? In SVGs, one needs to keep them apart. That's why we cannot just remove all casing.

**Comment by kapouer** [comment]
I'm storing some html string, then later I reload the page and modify the DOM, then I want to compare the modified DOM to the original html string:
`innerDiff.apply(dom, innerDiff.diff(dom, html))`

ending up comparing "div" with "DIV" which fails.

**Comment by icanfathom** [comment]
An example that fails for me as well:
```javascript
const el = document.createElement('div');
diff.apply(el, diff.diff(el, '<div></div>'));
```

Even though both are written as lowercase 'div', the call to `document.createElement('div')` creates an uppercase DIV.

**Comment by johanneswilm** [comment]
Hey, yes so the issue is that HTML is not case sensitive, but XHTML [1] and other XML such as SVG [2] are. So as long as we also support XML elements, we cannot really remove case sensitivity. It's possible we could make it a configuration option, but when enabled that then means you cannot process SVGs.

[1] https://medium.com/@shaiknadeem2003/html-vs-xhtml-understanding-the-key-differences-64e39010c908#:~:text=Syntax%20%26%20Rules,Whereas%20XHTML%20is%20case%2Dsensitive.

[2] https://www.ibm.com/docs/en/b2bis?topic=syntax-xml-rules

**Comment by johanneswilm** [comment]
> An example that fails for me as well

Can you not just use the string `<DIV></DIV>` instead? Does that not work?
