### ISSUE TITLE
adjacent text node agnostic merging

### ISSUE THREAD

**Issue by cjdelisle** [fiduswriter/diffDOM#52]
Starting this issue here to begin a conversation about text nodes. For the CryptPad use case we are pushing DiffDOM to it's limit by using it to patch changes to the DOM across the wire when people have typed in a contentEditable.
We have discovered an interesting issue that browsers like to split text nodes on occasions which don't always make sense. If we make a text node longer than a given length, the browser will decide to split it into two, if we hit backspace in the middle of a text node, the browser will decide to split it and then shorten the node before, rather than shifting the entire text node.

My gut feeling is that DiffDOM probably ought to be agnostic to adjacent text nodes when it merges. That is to say, it should see `["hel","lo ","world!"]` the same as `["hello"," world!"]`. Furthermore there is perhaps some performance to be gained by reusing the browser's trick when a few characters are removed from the middle of a text node to call `Text.splitText()` and then simply shorten the prior text node.

In any case, it would be nice if the adjacent text nodes in one DOM were not shoved into the other DOM which kills our cursor location and makes any sane Operational Transform quite impossible.

What do you think about this? Is considering adjacent text nodes as separate things a valued feature or is this something which you'd be open to a patch for?

**Comment by johanneswilm** [comment]
Hey @cjdelisle Sorry for late reply.

Actually, the need to be able to treat adjacent text nodes separately was one of the main reasons why we stopped using html-strings to descrive DOm-nodes and instead used the json representation. 

I did not know that browsers break long text nodes automatically, but it does happen a fair bit when using JS for editing operations, we found. 

What exactly is the problem with treating thems separately? If User A has a long text node and breaks it into two due to editing operations, would it not also make sense for User B and User C to have the same kind of separated text nodes in their browsers? The breaking will only happen during a text editing operation, right? So at that stage there will be a diff sent anyway, correct?
