### ISSUE TITLE
diff symmetry + addAttribute prevention + diffing children

### ISSUE THREAD

**Issue by ndvbd** [fiduswriter/diffDOM#86]
Firstly - great stuff you guys have made here.

A few things:

1. Symmetry: From what I've seen the .diff(src, target) + .apply(src, diff) makes the target to be **under** the src. So I think it's worth mentioning in the readme that the diff is between the tree under src and to the target, and not a diff between src <> target.

2. My need is as follows: I want to diff between the **children** of src to the **children** of target. I want that after applying the diff, the children of the target will be the children of src. How can I do this (efficiently)?

3. In another use case I wanted to apply the diff to the src element, but to create the structure of the tags (+text nodes), just without the tags attributes. In a similar way to whats the readme says I did:
```

dd = new diffDOM.DiffDOM({                                 
                                    preDiffApply: function (info) {
                                        if (info.diff.action === 'addAttribute') {
                                            return true;
                                        }
                                    }
                                });

```
But this hangs the CPU of the computer, and the browser tab gets stuck (and it doesn't finish). What am I doing wrong?

Thanks.

**Comment by johanneswilm** [comment]
Hey,

1. Your assumption is incorrect (if I understand it correctly). If you diff `<div id="fish"></div>` with `<div id="monkey"></div>` you will receive a working diff that you can apply. The one thing you cannot do is diff `<div></div>` with `<p></p>`. But this is a shortcoming of how browsers work, as there is no way to exchange the type of an existing dom node. You are welcome to create a PR explaining this more in detail in case you find it's not sufficiently explained.

2. So `src` and `target` have different attributes and you want to ignore those and only apply the changes to the children? Take a look at the diffs. It's an array and you'll want to filter it for items whose `route` has a length or that correspond to certain types before applying.

3. The diffing works this way: it finds the first diff, applies that diff within it's virtual representation of the DOM. Then finds the next diff, applies the diff in the virtual DOM, etc. until both nodes are equal. It then hands you the entire array of changes. What you are doing there is telling the system that you already applied the added attribute, when that is really a lie and you haven't applied it. So for the next diff, it will find that same difference again. And next time again. And again. All the time into infinity. If you want to use that function you really need to make sure that you really do apply the diff yourself, or return false so that the system can do it for you. I'm guessing you are doing this to achieve #2 - in that case filter the diff array instead as described above.

**Comment by johanneswilm** [comment]
@ndvb I am assuming that I answered this in sufficient detail, so I'll close this issue. Please reopen if you find it not being answered quite enough so far.

**Comment by ndvbd** [comment]
Hi @johanneswilm  - not sure I understood (3). How can I tell the library to apply the changes, but not to set attributes, just the structure of the tags and the text elements? (I want to create a "shadow" element for a div, that contains everything but the attributes/styles)

**Comment by johanneswilm** [comment]
@ndvbd Take a look at the diff output. It's an array of changes. You need to filter out those that change attributes before applying.

**Comment by ndvbd** [comment]
Did it. Works well!
